---

- name: Apache server installed
  hosts: webservers
  become: yes
  gather_facts: yes
  tasks:
  - name: Latest apache version installed
    yum:
      name: httpd
      state: latest
    tags: 
    - packages

  - name: apache server started and enabled
    systemd:
      name: httpd
      state: started
      enabled: yes
    tags:
    - service

  - name: index.html deployed
    copy:
      src: index.html
      dest: /var/www/html/
    tags:
    - deploy

  - debug: msg="Always run"
    tags:
    - always
