---
# tasks file for apache-role
- name:  httpd installed
  import_tasks: install-redhat.yml
  when: ansible_os_family|lower == "redhat"
- name: apache2 installed
  import_tasks: install-debian.yml
  when: ansible_os_family|lower == "debian"
- name: configure httpd
  import_tasks: configure-redhat.yml
  when: ansible_os_family|lower == "redhat"
- name: configure apache2
  import_tasks: configure-debian.yml
  when: ansible_os_family|lower == "debian"

- name: deploy index.html
  template: src=index.html.j2 dest=/var/www/html/index.html

- name: httpd started and enabled
  systemd: name=httpd state=started enabled=true
  when: ansible_os_family|lower == "redhat"

- name: apache started and enabled
  systemd: name=apache2 state=started enabled=true
  when: ansible_os_family|lower == "debian"
